package twentyfive

import aoc.twentyfive.Day7

class Day7Test extends munit.FunSuite {
  val sample = """.......S.......
                 |.......|.......
                 |.......^.......
                 |...............
                 |......^.^......
                 |...............
                 |.....^.^.^.....
                 |...............
                 |....^.^...^....
                 |...............
                 |...^.^...^.^...
                 |...............
                 |..^...^.....^..
                 |...............
                 |.^.^.^.^.^...^.
                 |...............""".stripMargin

  test("example") {
    val p = Day7.parse(sample)
    assertEquals(Day7.part1(p), 21L)
  }

  test("example p2 ") {
    val p = Day7.parse(sample)
    assertEquals(Day7.part2(p), 40L)
  }

  test("more p2") {
    val sample =
      Day7.parse(""".......S.......
                   |.......|.......
                   |.......^.......
                   |...............
                   |......^.^......
                   |...............
                   |.....^.^.^.....
                   |...............""".stripMargin)

    Day7.part2(sample)
  }
}
